# Generated by Django 2.1.1 on 2018-12-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='target_customer',
            field=models.TextField(default='Not specified'),
            preserve_default=False,
        ),
    ]
