# Generated by Django 2.1.1 on 2018-12-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_target_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.TextField(default='Uncategorized'),
            preserve_default=False,
        ),
    ]
