# Generated by Django 2.1.1 on 2019-01-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='target_customer',
            field=models.TextField(max_length=200),
        ),
    ]
